safe:        true
auto:        true
server:      false
server_port: 4000
baseurl:     /choropleth
url:         http://localhost:4000

source:      .
destination: ./_site

future:      true
lsi:         false
pygments:    true
markdown:    redcarpet
permalink:   pretty

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]